on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install build deps
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libreadline-dev
      - name: compile
        run: make
      - name: run tests
        run: |
          scripts/run-tests